{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Warnings",
   "type": "timeseries",
   "description": "If any of these metrics are close to 1, then the system needs immediate attention.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) / 8",
     "legendFormat": "CPU load"
    },
    {
     "expr": "clamp_min((1-(node_memory_MemAvailable_bytes/(node_memory_MemTotal_bytes - 1.6*10^10))), 0)",
     "legendFormat": "RAM load"
    },
    {
     "expr": "zfs_pool_allocated_bytes / (zfs_pool_allocated_bytes + zfs_pool_free_bytes)",
     "legendFormat": "Storage load ({{pool}})"
    },
    {
     "expr": "(node_hwmon_temp_celsius - 25) / (node_hwmon_temp_max_celsius - 25)",
     "legendFormat": "Heat load"
    },
    {
     "expr": "sum by(zpool) (node_zfs_zpool_state{state=~\"degraded|faulted|unavail\"})",
     "legendFormat": "Zpool breakage ({{zpool}})"
    },
    {
     "expr": "sum(systemd_unit_state{state=\"failed\"})",
     "legendFormat": "Systemd failures"
    }
   ]
  },
  {
   "title": "CPU Accounting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" }
   ]
  },
  {
   "title": "Storage utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "zfs_pool_allocated_bytes", "legendFormat": "Allocated bytes ({{pool}})" },
    { "expr": "zfs_pool_size_bytes", "legendFormat": "Total ({{pool}})" }
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "CPU Temp" },
    { "expr": "smartctl_device_temperature", "legendFormat": "HDD {{device}} temp" },
    { "expr": "node_hwmon_temp_crit_celsius", "legendFormat": "CPU critical temp" }
   ]
  },
  {
   "title": "Systemd unit status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "systemd_unit_state" }
   ]
  }
 ]
}